![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.5


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [2]:
# your code goes here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#np.array([0] * 10)
np.zeros(10)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [4]:
# your code goes here
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [8]:
# your code goes here
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])

In [7]:
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [9]:
# your code goes here
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [12]:
# your code goes here
#numpy.ones_like
#Return an array of ones with the same shape and type as a given array.
X = np.arange(6)
np.ones_like(X)

array([1, 1, 1, 1, 1, 1])

In [15]:
X = np.arange(4, dtype=np.int)

np.ones_like(X)

array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [16]:
# your code goes here
np.array([2,2], dtype=np.int)

array([2, 2])

In [17]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [20]:
# your code goes here
np.ones([4,4], dtype=np.int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [21]:
np.ones([4,4], dtype=np.int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [24]:
# your code goes here
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)
np.ones_like(X) * 7

array([[7, 7, 7],
       [7, 7, 7]])

In [25]:
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

numpy.eye(R, C = None, k = 0, dtype = type <‘float’>) : Return a matrix having 1’s on the diagonal and 0’s elsewhere w.r.t. k.

R : Number of rows

C : [optional] Number of columns; By default M = N

k : [int, optional, 0 by default] Diagonal we require; k>0 means diagonal above main diagonal or vice versa.

dtype : [optional, float(by Default)] Data type of returned array.

In [28]:
# your code goes here
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

numpy.identity(n, dtype = None) : Return a identity matrix i.e. a square matrix with ones on the main diagonal


n     : [int] Dimension n x n of output array  
dtype : [optional, float(by Default)] Data type of returned array
default dtype is float64

In [27]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [32]:
# your code goes here
np.random.randint(10, size=(3))

array([7, 9, 3])

In [33]:
np.random.randint(10, size=3)

array([0, 7, 5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [37]:
# your code goes here
np.random.randn(3,3,3)

array([[[ 1.15881778, -0.58710388,  1.12641189],
        [-0.04968976, -1.17715401, -0.55745363],
        [-1.37605832,  2.04721773, -0.52785271]],

       [[ 1.65967738, -0.73218069,  1.02795775],
        [ 0.12281791, -0.04930691, -1.63308523],
        [ 1.56988867,  0.10248559, -1.68371259]],

       [[ 0.17915987, -0.89318609,  0.90379952],
        [ 0.79996892,  1.13698561, -0.4304483 ],
        [ 0.17867002, -0.72815905,  2.94174422]]])

In [38]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 0.44425981, -0.06384244,  0.02034386],
        [ 0.03138076,  1.50617883, -0.32258559],
        [ 0.2383755 , -0.09520456,  1.15718347]],

       [[-1.0564465 ,  0.27150039, -0.59263289],
        [ 1.37401339, -1.40062416,  0.40372835],
        [ 0.90766949,  0.08610198, -0.89050704]],

       [[ 0.44374756, -0.86846795,  0.46206042],
        [ 0.35504005,  1.6108245 , -1.48493378],
        [-1.5267917 ,  0.23216144, -0.47522557]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [41]:
# your code goes here
X = [22, 2022]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[22, 2022] <class 'list'>
[  22 2022] <class 'numpy.ndarray'>


In [42]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [52]:
# your code goes here
X = np.array([10, 10, 10, 10])
Y = np.array(X)
print(X, id(X))
print(Y, id(Y)) # different id

Y[1] = 11
print(X, id(X))
print(Y, id(Y)) # different id
X[2] = 12
print(X, id(X))
print(Y, id(Y)) # different id

print(X, type(X))
print(Y, type(Y))

[10 10 10 10] 139996519267504
[10 10 10 10] 139996519267584
[10 10 10 10] 139996519267504
[10 11 10 10] 139996519267584
[10 10 12 10] 139996519267504
[10 11 10 10] 139996519267584
[10 10 12 10] <class 'numpy.ndarray'>
[10 11 10 10] <class 'numpy.ndarray'>


np.copy()
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

In [53]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

Y[1] = 11
print(X, id(X))
print(Y, id(Y)) # different id

X[2] = 12
print(X, id(X))
print(Y, id(Y)) # different id

print(X, type(X))
print(Y, type(Y))

[5 2 3] 139996519644336
[5 2 3] 139996519674704
[5 2 3] 139996519644336
[ 5 11  3] 139996519674704
[ 5  2 12] 139996519644336
[ 5 11  3] 139996519674704
[ 5  2 12] <class 'numpy.ndarray'>
[ 5 11  3] <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [54]:
# your code goes here
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

**numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)**

Parameters

start: integer or real, optional
Start of interval. The interval includes this value. The default start value is 0.

stop: integer or real
End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

step: integer or real, optional
Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.

dtypedtype:
The type of the output array. If dtype is not given, infer the data type from the other input arguments.

likearray_like:
Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

New in version 1.20.0.

Returns
arangendarray
Array of evenly spaced values.

For floating point arguments, the length of the result is ceil((stop - start)/step). Because of floating point overflow, this rule may result in the last element of out being greater than stop.

In [57]:
# your code goes here
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [58]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

There is no option or argument in both the sort() functions to change the sorting order to decreasing order. So, to sort a numpy array in descending order we need to sort it and then use [::-1] to reverse the sorted array. It will give the effect of sorting in descending order

In [66]:
myArray = np.arange(1,11)
myArray[::-1].sort()
print(myArray)

[10  9  8  7  6  5  4  3  2  1]


Use the syntax array[::-1] to reverse array

In [64]:
# your code goes here
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [67]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

numpy.reshape(a, newshape, order='C')[source]

Gives a new shape to an array without changing its data.

In [68]:
# your code goes here
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

**Method 1**: Using size and itemsize attributes of NumPy array.

size: This attribute gives the number of elements present in the NumPy array.

itemsize: This attribute gives the memory size of one element of NumPy array in bytes.

x = np.array([100,20,34])
  
print("Size of the array: ",
      x.size)
  
print("Memory size of one array element in bytes: ",
      x.itemsize)
  
Memory size of numpy array in bytes:

print("Memory size of numpy array in bytes:", x.size * x.itemsize)

In [72]:
# your code goes here
Z = np.array([22,2022])
print("Size: ",Z.size)
print("Memory size of one element of the array (in Bytes): ",Z.itemsize)
print("Memory size of numpy array in bytes:", Z.size * Z.itemsize)

Size:  2
Memory size of one element of the array (in Bytes):  8
Memory size of numpy array in bytes: 16


**Method 2**: Using nbytes attribute of NumPy array.
nbytes: This attribute gives the total bytes consumed by the elements of the NumPy array.

x = np.array([100, 20, 34])
  
print("Memory size of a NumPy array:",
      x.nbytes)

In [75]:
Z = np.array([22,2022])
print("Memory size of numpy array in bytes:", Z.nbytes)

Memory size of numpy array in bytes: 16


In [77]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))
print("Memory size of numpy array in bytes:", Z.nbytes)

800 bytes
Memory size of numpy array in bytes: 800


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [79]:
# your code goes here
X = np.array([1,2,3,4,5])
X[0]

1

In [80]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [82]:
# your code goes here
X = np.array([1,2,3,4,5])
X[-1]

5

In [83]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

'E'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [84]:
# your code goes here
X = np.array([1,2,3,4,5])
X[0:3] #last is not included

array([1, 2, 3])

In [85]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [88]:
# your code goes here
X = np.array([1,2,3,4,5])
X[1:-1] #last is not included

array([2, 3, 4])

In [89]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [90]:
# your code goes here
X = np.array([1,2,3,4,5])
X[::-1]

array([5, 4, 3, 2, 1])

In [91]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

odd_position_elements = a_list[1::2]

In [95]:
# your code goes here
X = np.array([0,1,2,3,4,5])
X[1::2]

array([1, 3, 5])

In [94]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [101]:
# Numpy matrix
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29],
    [30, 35, 39]
])
A[0]#Getting the first row

array([10, 15, 19])

In [99]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [102]:
# your code goes here
# Numpy matrix
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29],
    [30, 35, 39]
])
A[-1]#Getting the last row

array([30, 35, 39])

In [103]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [105]:
# your code goes here
# Numpy matrix
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29],
    [30, 35, 39]
])
A[0][0]#Getting the first element on first row

10

Using dimensional selection of Numpy

In [107]:
# Numpy matrix
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29],
    [30, 35, 39]
])
A[0,0]#Getting the first element on first row

10

In [108]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [110]:
# your code goes here
# Numpy matrix
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29],
    [30, 35, 39]
])
A[-1][-1]#show the last element on last row

39

Using dimensional selection of Numpy

In [111]:
# your code goes here
# Numpy matrix
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29],
    [30, 35, 39]
])
A[-1,-1]

39

In [112]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [128]:
# your code goes here
# Numpy matrix
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29],
    [30, 35, 39]
])
A[[1,-2]] #Not working well

array([[20, 25, 29],
       [20, 25, 29]])

In [127]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [132]:
# your code goes here
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29],
    [30, 35, 39]
])
A[0:2, 0:2]

array([[10, 15],
       [20, 25]])

In [133]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [139]:
# your code goes here
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29],
    [30, 35, 39]
])
A[1:, 1:]

array([[25, 29],
       [35, 39]])

In [140]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [142]:
# your code goes here
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29],
    [30, 35, 39]
])
np.array(A, np.float)

array([[10., 15., 19.],
       [20., 25., 29.],
       [30., 35., 39.]])

In [143]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

array([-5., -3.,  0., 10., 40.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [144]:
# your code goes here
A = np.array([10, 15, 19])
A[::-1]

array([19, 15, 10])

In [145]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [150]:
# your code goes here
A =np.array([15, 13, 19])
np.sort(A)


array([13, 15, 19])

In [148]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [155]:
# your code goes here
X =np.array([15, 13, 19, 22, 25, 26])
X[4] = 1
print(X)

[15 13 19 22  1 26]


In [156]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [157]:
# your code goes here
X = np.array([10, 20, 30, 50])
X[3] = 40
X

array([10, 20, 30, 40])

In [158]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [163]:
# your code goes here
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29], # 1
    [30, 35, 39]  # 2
])

A[-1] = 1
print(A)

[[10 15 19]
 [20 25 29]
 [ 1  1  1]]


In [164]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [165]:
# your code goes here
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29], # 1
    [30, 35, 39]  # 2
])

A[-1, -1] = 1
print(A)

[[10 15 19]
 [20 25 29]
 [30 35  1]]


In [166]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [167]:
# your code goes here
A = np.array([
#.   0. 1. 2
    [10, 15, 19], # 0
    [20, 25, 29], # 1
    [30, 35, 39]  # 2
])

A + 5
print(A)

[[10 15 19]
 [20 25 29]
 [30 35 39]]


In [168]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [178]:
# your code goes here
A = np.array([-1, 1, -2, 2, -3, 3])
mask = A < 0
print(mask)

[ True False  True False  True False]


In [171]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [180]:
# your code goes here
X = np.array([-1, 1, -2, 2, -3, 3])
X[X < 0]

array([-1, -2, -3])

In [181]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [183]:
# your code goes here
X = np.array([-1, 1, -2, 2, -3, 3, -4, 4, -5, 5, -6, 6])
X[X > 5]

array([6])

In [184]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [185]:
# your code goes here
X = np.array([-1, 1, -2, 2, -3, 3, -4, 4, -5, 5, -6, 6])
X[X > X.mean()]

array([1, 2, 3, 4, 5, 6])

In [186]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [193]:
# your code goes here
X = np.array([-1, 1, -2, 2, -3, 3, -4, 4, -5, 5, -6, 6, -7, 7, -8, 8, -9, 9, -10, 10])
X[(X == 2) | (X == 10)]

array([ 2, 10])

In [192]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [194]:
# your code goes here
X = np.array([0, -1, 1, -2, 2, -3, 3, -4, 4, -5, 5, -6, 6, -7, 7, -8, 8, -9, 9, -10, 10])
X.all()#The numpy. all() function tests whether all array elements along the mentioned axis evaluate to True

False

In [195]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [197]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

In [198]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [201]:
# your code goes here
X = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
X.sum()

55

In [200]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements
Mean = media, promedio

In [209]:
# your code goes here
X = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(X.sum() / X.size)
print(X.mean())




5.0
5.0


In [212]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [216]:
# your code goes here
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A.sum(axis=0)
#sum of the first column = 1 + 4 + 7 = 12
#sum of the second column = 2 + 5 + 8 = 15
#sum of the third column = 3 + 6 + 9 = 18
#Result: array([12, 15, 18])

array([12, 15, 18])

In [214]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [217]:
# your code goes here
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A.mean(axis=1)# remember: axis=0 columns; axis=1 rows

array([2., 5., 8.])

In [218]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [221]:
# your code goes here
A = np.array([22, 1, 35])
A.max()

35

In [222]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)